# Generated by Django 3.0 on 2021-06-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vdgoobject',
            table='to_ch_addr_object',
        ),
    ]
