# Generated by Django 3.0 on 2021-06-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0002_auto_20210604_1546'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='undonereason',
            table='web_vdgo_undone_spr',
        ),
    ]
