# Generated by Django 3.0 on 2021-06-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0003_auto_20210610_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileinfo',
            options={'managed': False, 'ordering': ['file_category', 'filename'], 'verbose_name': 'Файл объекта', 'verbose_name_plural': 'Файлы объекта'},
        ),
    ]
