# Generated by Django 3.0 on 2021-06-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0004_auto_20210610_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='BypassBuffer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_bypass', models.IntegerField()),
                ('id_obj', models.IntegerField()),
                ('id_exec', models.IntegerField()),
                ('date_action', models.DateTimeField()),
                ('exec_vdgo', models.SmallIntegerField()),
                ('undone_reason', models.SmallIntegerField()),
                ('fixed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'web_vdgo_buff_bypass',
            },
        ),
    ]
