# Generated by Django 3.0 on 2021-06-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0006_auto_20210617_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentmodel',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Модель оборудования', 'verbose_name_plural': 'Модели оборудования'},
        ),
    ]
