# Generated by Django 3.0 on 2021-06-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0007_auto_20210618_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInfoPrev',
            fields=[
                ('id', models.IntegerField(db_column='id_st', primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_manufacturer', models.CharField(db_column='name_izg', max_length=80, verbose_name='Изготовитель')),
                ('prev_model', models.CharField(db_column='model', max_length=50, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Предыдущее значение оборудования',
                'verbose_name_plural': 'Предыдущее значения оборудований',
                'db_table': 'web_vdgo_ob_prev',
                'managed': False,
            },
        ),
    ]
