# Generated by Django 3.0 on 2021-06-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0008_auto_20210618_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInfoBuffer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_bypass', models.IntegerField()),
                ('id_st', models.IntegerField()),
                ('id_izg', models.IntegerField(default=0)),
                ('id_model', models.IntegerField(default=0)),
                ('podvod', models.BooleanField(default=0)),
                ('z_num', models.CharField(max_length=32)),
                ('k_count', models.SmallIntegerField(default=0)),
                ('Pwr', models.FloatField(default=0)),
                ('Expl', models.SmallIntegerField(default=0)),
                ('dopinf', models.TextField(blank=True)),
                ('d_ust', models.DateTimeField(default='2050-01-01 00:00:00')),
                ('d_otkl', models.DateTimeField(default='2050-01-01 00:00:00')),
                ('tip_kam', models.SmallIntegerField(default=0)),
                ('m_ust', models.SmallIntegerField(default=0)),
                ('pokaz', models.IntegerField(default=0)),
                ('d_pokaz', models.DateTimeField(default='2050-01-01 00:00:00')),
                ('klapan', models.BooleanField(default=False)),
                ('kontr_sr', models.SmallIntegerField(default=0)),
                ('user_add', models.SmallIntegerField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('fixed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'web_vdgo_buff_ob',
            },
        ),
    ]
