# Generated by Django 3.0.10 on 2021-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bypass', '0009_auto_20210618_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinfobuffer',
            name='z_num',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterModelTable(
            name='equipmentmodel',
            table='vdg_model',
        ),
    ]
