export const GET_EQUIPMENT = 'GET_EQUIPMENT' 

export const GET_IMAGES = 'GET_IMAGES' 
export const GET_REASONS = 'GET_REASONS'
export const GET_UNITS = 'GET_UNITS'
export const SET_UNIT = 'SET_UNIT'
export const GET_EXECUTORS = 'GET_EXECUTORS'
export const SET_REGISTER_EXECUTOR = 'SET_REGISTER_EXECUTOR'
export const SET_REGISTER_USERNAME = 'SET_REGISTER_USERNAME'
export const SET_REGISTER_PASSWORD = 'SET_REGISTER_PASSWORD'
export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const GET_ITD = 'GET_ITD'

export const GET_BYPASSES = 'GET_BYPASSES' 
export const GET_BYPASS_COUNT = 'GET_BYPASS_COUNT'
export const CHANGE_DATE = 'CHANGE_DATE'

export const GET_OBJECT = 'GET_OBJECT'
export const GET_OBJECT_DOG_TYPE = 'GET_OBJECT_DOG_TYPE'

export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGOUT = 'LOGOUT' 

export const LOADING_SPINNER_SHOW_MUTATION = 'LOADING_SPINNER_SHOW_MUTATION'
export const LOADING_SPINNER_HIDE_MUTATION = 'LOADING_SPINNER_HIDE_MUTATION' 

export const UPDATE_STATUS = 'UPDATE_STATUS' 
export const SET_REASON = 'SET_REASON'
export const SET_NEW_EMAIL_VDGO = 'SET_NEW_EMAIL_VDGO'
export const UPDATE_EMAIL_VDGO = 'UPDATE_EMAIL_VDGO'
export const SET_NEW_PHONE_VDGO = 'SET_NEW_PHONE_VDGO'
export const UPDATE_PHONE_VDGO ='UPDATE_PHONE_VDGO' 

export const POST_IMAGE = 'POST_IMAGE'
export const POST_ITD = 'POST_ITD' 
export const REMOVE_IMAGE ='REMOVE_IMAGE'
export const REMOVE_FILE = 'REMOVE_FILE'

export const ERROR = 'ERROR'
export const GET_USERS = 'GET_USERS'
export const ADD_USER = 'ADD_USER'