# Generated by Django 3.0 on 2021-06-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210604_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('boss', 'Руководитель'), ('user', 'Пользователь')], default='user', max_length=9, verbose_name='Роль'),
        ),
    ]
